# Generated by Django 4.1.4 on 2024-01-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_certyfikowany_narkoman',
            field=models.ImageField(blank=True, null=True, upload_to='rank_images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image_certyfikowany_wielki_chlop',
            field=models.ImageField(blank=True, null=True, upload_to='rank_images/CertyfikowanyWielkiChlop.jpg'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.CharField(blank=True, choices=[('-', '-'), ('CertyfikowanyWielkiChłop', 'CertyfikowanyWielkiChłop'), ('CertyfikowanyNarkoman', 'CertyfikowanyNarkoman')], default='-', max_length=50, null=True),
        ),
    ]
