# Generated by Django 4.1.4 on 2024-01-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0003_customuser_image_certyfikowany_narkoman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.CharField(blank=True, choices=[('-', '-'), ('CertyfikowanyWielkiChlop', 'CertyfikowanyWielkiChlop'), ('CertyfikowanyNarkoman', 'CertyfikowanyNarkoman')], default='-', max_length=50, null=True),
        ),
    ]
